version: "3.7"

services:

    user_app:
      build: ./
      restart: always
      ports:
        - 8080:80
      depends_on:
        - user_db
    
    user_db:
      image: mysql
      container_name: user_db
      command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=32505856
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: admin
      ports:
        - 3306:3306
